
<style>
.list {
  list-style: none!important;
}
.list li::before {
  content: "\2022";
  color: #9D81EB;
  font-weight: bold;
  display: inline-block;
  font-size: 30px;
  width: 1em;
  margin-left: -1em;
}
</style>

<article>
  <h1 id="politica-de-privacidade">Política de Privacidade SocialBase</h1>
  <p>Nesta Política de Privacidade, o termo “<a href="http://www.socialbase.com.br" target="_blank" rel="noreferrer">www.socialbase.com.br</a>” se refere ao nosso website corporativo, cuja homepage está localizada em <a href="http://www.socialbase.com.br" target="_blank" rel="noreferrer">www.socialbase.com.br</a>; já a rede SocialBase, ou apenas rede, se refere à solução de comunicação interna baseada em uma rede social corporativa, ou seja, o nosso produto; os termos “nos”, “nós” ou “nosso” se referem a SocialBase Soluções em Tecnologia S.A., proprietária do <a href="http://www.socialbase.com.br" target="_blank" rel="noreferrer">www.socialbase.com.br</a>, e os termos “você” ou “usuário” se referem ao usuário da rede ou visitante do <a href="http://www.socialbase.com.br" target="_blank" rel="noreferrer">www.socialbase.com.br</a>. As informações dessa Política de Privacidade se aplicam ao nosso website corporativo e às redes de nossos clientes.</p>
  <h2 id="tratamento-de-dados">Tratamento de dados através da Rede Social Corporativa SocialBase </h2>
  <p>Sua privacidade é fundamental para a SocialBase. Cada empresa ou organização que utiliza a rede da SocialBase está localizada em uma rede separada, o que garante a privacidade de seus usuários e do conteúdo publicado por cada um na rede. Ela, a rede, funciona da seguinte forma:</p>
  <ul class="list">
    <li>Sua rede é definida sempre pelo nome da empresa seguida por “.socialbase.com.br”. Já o acesso a sua rede, por padrão, é executado pelo domínio do e-mail de sua empresa ou organização. Por exemplo, todos os usuários que se cadastrarem com um endereço de e-mail “@xxxxxxx.com.br” farão parte da rede “xxxxxxx.socialbase.com.br”. Para fazer parte de uma rede, você deve confirmar seu endereço de e-mail.</li>
    <li>É possível que sua rede possua uma URL diferente, ou que seu acesso não seja feito por e-mail. Nesses casos, procure a equipe de comunicação interna da sua empresa.</li>
    <li>Somente as pessoas em sua rede podem visualizar os seus perfis e feeds.</li>
    <li>Não compartilhamos suas informações privadas com companhias de publicidade. Isso inclui seu endereço de e-mail e os endereços de e-mail de outras pessoas em sua rede.</li>
    <li>As empresas que contratam a rede SocialBase detêm a propriedade do conteúdo do usuário criado por seus colaboradores a partir do momento que estes autorizam o tratamento de seus dados, conforme Lei Nº 13.709 de 13/08/2018. Até esse ponto, os usuários detêm propriedade do seu próprio conteúdo. A empresa SocialBase não detém a propriedade de tal conteúdo. Os Administradores da rede podem solicitar que mensagens publicadas em sua rede sejam exportadas de forma segura para um destino designado pela empresa para quaisquer fins, inclusive fins de arquivo e backup.</li>
    <li>O acesso ao banco de dados é fornecido somente aos nossos técnicos, caso a caso, para solucionar questões técnicas específicas, ou conforme possa ser exigido pela lei.</li>
    <li>A empresa SocialBase instituiu medidas para proteger a segurança dos dados de cada rede.</li>
  </ul>
  <h2 id="uso-da-rede-social">Informações referentes ao uso da Rede Social Corporativa SocialBase</h2>
  <ul class="list">
    <li>As empresas que implementam sua rede podem impor requisitos adicionais de segurança além daqueles descritos nesta Política de Privacidade. Exemplos de tais restrições incluem sessões seguras, políticas de senha e acesso restrito ao intervalo de protocolo interno de sua rede privada virtual.</li>
    <li>Você fornecerá Informações Pessoais para o preenchimento do seu perfil de usuário, tais como seu nome e endereço de e-mail, ao registrar uma conta como usuário da rede. Você também pode escolher adicionar outras informações, como uma foto, a seu perfil.</li>
    <li>De forma geral, você pode nos fornecer dois tipos de informação: o conteúdo do usuário, que pode incluir Informações Pessoais, e Informações sobre Uso da Rede, ambos apresentados em maiores detalhes abaixo:</li>
    <li>Será solicitado que você forneça Nome e E-mail ao se registrar na rede. Poderemos executar a coleta de informações pessoais através de pesquisas, questionários, atividades executadas no feed de conteúdos gerados pelo usuário, e do próprio perfil preenchido pelo usuário.</li>
    <li>Podemos ainda utilizar mecanismos de computação para obter Informações sobre Uso da Rede, sendo eles:</li>
    <li>Cookies: Um cookie é um documento de texto muito pequeno, que frequentemente inclui um identificador único anônimo. O SocialBase emprega o uso de cookies de “sessão” e cookies “persistentes”. Um cookie persistente permanece em seu disco rígido após fechar seu navegador. Cookies persistentes podem ser utilizados por seu navegador em visitas posteriores a rede. Eles podem ser removidos seguindo as orientações de seu navegador da Web. Um cookie de sessão é temporário e desaparece após você fechar seu navegador. Ao visitar nossa rede, nossa aplicação pode pedir permissão ao seu computador para empregar o uso de um cookie de sessão ou persistente. Nossa rede então enviará um cookie para seu navegador, se as preferências de seu navegador permitirem, mas para proteger sua privacidade seu navegador somente permite que nossa rede acesse os cookies que já lhe enviou e não os cookies enviados a você por outros websites. A maioria dos navegadores da Web pode ser ajustada para lhe informar quando um cookie lhe foi enviado e lhe dar a oportunidade de recusá-lo. Entretanto, recusar um cookie pode, em alguns casos, impedi-lo de usar ou ter um impacto negativo na exibição ou função de nossa rede ou em algumas de suas áreas ou recursos.</li>
    <li>GIFs Transparentes: também conhecido como “sinalizadores da web” – “web beacons” ou “pixel tags”, um GIF Transparente é tipicamente uma imagem transparente de um pixel localizada em uma webpage, em um e-mail ou outro tipo de mensagem, que nos ajuda a verificar a visualização de um indivíduo ou recebimento de uma webpage ou mensagem. GIFs Transparentes nos permitem saber se você visualizou uma webpage antes de visitar nossa rede e podem nos permitir relacionar tais informações a outras, inclusive suas Informações Pessoais. Utilizamos informações fornecidas de GIFs Transparentes para possibilitar relatórios mais precisos, melhorar a eficiência de nosso marketing e tornar a rede melhor para nossos usuários.</li>
    <li>Endereço de IP e Dados Clickstream: nossos servidores automaticamente coletam dados sobre seu endereço de Protocolo de Internet ao nos visitar. Quando você solicita páginas de nossa rede, nossos servidores podem registrar seu Endereço de IP e, por vezes, o nome de seu domínio. Nosso servidor também pode registrar a página de referência que fez a sua conexão conosco (por exemplo, outro website ou um mecanismo de busca); as páginas que você visitou nesta rede; o website que você visita após este ou aquele website; outras informações sobre o tipo de navegador da Web, computador, plataforma, software relacionado e configurações que você está utilizando; quaisquer termos de busca que você tiver digitado nesta rede ou em um website de referência; e outras atividades de uso da Web e dados registrados por nossos servidores da Web. Usamos essas informações para administração do sistema interno, para ajudar a diagnosticar problemas com nossos servidores e para administrar nossa rede. Tais informações também podem ser usadas para reunir informações demográficas amplas, tais como o país de origem e o Provedor de Serviços de Internet. Também podemos relacionar essas informações com Informações Pessoais. Toda e qualquer uma dessas atividades com relação às informações de uso da rede acima descritas pode ser realizada em nosso nome por nossos prestadores de serviços terceirizados.</li>
    <li>Utilizaremos suas Informações Pessoais para responder suas solicitações e para lhe fornecer nossas ofertas de produtos e serviços. Podemos combinar as informações que coletamos de você através de diferentes meios ou em momentos diferentes, inclusive Informações Pessoais e Informações sobre Uso da Rede, e usaremos tais informações junto com as que foram obtidas de outras fontes, inclusive (sem limitação) qualquer um de nossas outras redes e terceiros.</li>
    <li>Além disso, podemos analisar o comportamento do usuário como uma medida do interesse e uso de nossa rede e e-mails, individual e coletivamente. A SocialBase não compartilhará, alugará ou venderá suas Informações Pessoais a outras partes.</li>
    <li>Caso tenha quaisquer perguntas ou dúvidas referentes a esta Política de Privacidade, você deve primeiramente fazer contato por email através do endereço ‘<a href="mailto:contato@SocialBase.com.br">contato@socialbase.com.br</a>’ ou enviar uma correspondência para: Rod Admar Gonzaga, 440B - Sala 201, Florianópolis-SC, CEP: 88034-000.</li>
  </ul>
  <h2 id="acesso-website">Informações referentes ao acesso do website www.socialbase.com.br</h2>
  <p>Ao visitar nosso website, podemos coletar informações de seu computador referentes à sua visita. Tais informações nos ajudam a determinar informações sobre como você encontrou nosso website, a data na qual você o visitou e mecanismos de busca que podem ter lhe levado a ele. Coletamos tais informações a fim de continuamente melhorar e aumentar a funcionalidade do <a href="http://www.socialbase.com.br" target="_blank" rel="noreferrer">www.socialbase.com.br</a>.</p>
  <h2 id="informacoes-de-terceiros">Compartilhando Informações com Terceiros</h2>
  <p>Podemos utilizar parceiros terceirizados para nos ajudar a operar e manter nossa rede e website e para entregar nossos produtos e serviços. Também podemos compartilhar suas Informações Pessoais e Informações sobre Uso da Rede com nossos prestadores de serviços e outros terceiros (“Partes Afiliadas”) que fornecem produtos ou serviços para esta rede e website ou através dele ou para nosso negócio (tais como empresas de hospedagem de websites ou banco de dados, empresas de hospedagem de listas de endereços, prestadores de serviços de comunicação, prestadores de serviços de e-mail, empresas de análise, empresas de distribuição, empresas de logística, empresas de processamento de cartões de crédito e outros prestadores de serviços semelhantes que utilizam tais informações em nosso nome).</p>
  <p>Os prestadores de serviços terceirizados estão contratualmente proibidos de utilizar ou divulgar as Informações Pessoais e Informações sobre Uso da Rede, exceto conforme necessário para realizar os serviços em nosso nome ou para cumprir requisitos legais, ou de outra forma sujeitos aos termos desta Política de Privacidade.</p>
  <h2 id="estatistica-empregada">Estatística Agregada</h2>
  <p>Podemos divulgar estatísticas agregadas de dados com identificação não pessoal relativas ao comportamento do usuário como uma medida do interesse e uso de nosso website, nossa rede e e-mails a terceiros na forma de dados agregados, tais como padrões gerais ou relatórios demográficos, que não descrevem ou identificam qualquer usuário individual. As informações relativas a estatísticas agregadas podem ser coletadas através do uso de cookies de terceiros e outros dispositivos de rastreamento de terceiros.</p>
  <h2 id="divulgacao-obrigatoria">Divulgação Legalmente Obrigatória</h2>
  <p>Podemos divulgar suas Informações Pessoais caso seja exigido fazê-lo por lei ou por citação ou se acreditarmos que tal ação é necessária para: (a) estar em conformidade com a lei, cumprir uma ordem ou decisão judicial ou cumprir um processo judicial que foi entregue através de citação a nós ou a Partes Afiliadas; (b) proteger e defender nossos direitos e propriedades, a rede, os usuários da rede e/ou nossas Partes Afiliadas; ou (c) atuar nas circunstâncias para proteger a segurança dos usuários de nossa rede, a nós ou a terceiros.</p>
  <h2 id="dados-pessoais">Consentimento para Transferência Internacional e Processamento de Dados Pessoais</h2>
  <p>Ao nos fornecer Informações Pessoais através de nossa rede, você concorda que elas podem ser utilizadas por nós e por nossas Partes Afiliadas para os fins descritos neste documento e compreende e consente ainda com a coleta, manutenção, processamento e transferência de tais informações no Brasil e em outros países e territórios e para tais locais, que podem ter leis de privacidade diferentes das do Brasil e que podem proporcionar níveis variados de proteção para suas Informações Pessoais. Independentemente das leis em vigor nesses países, trataremos a privacidade de suas informações de acordo com esta Política de Privacidade. Ao fornecer suas Informações Pessoais para nosso website ou rede, você consente com nossa transmissão e processamento de suas informações em qualquer jurisdição, de acordo com esta Política de Privacidade.</p>
  <h2 id="informacoes-de-seguranca">Informações gerais a respeito de segurança empregada pela SocialBase</h2>
  <ul class="list">
    <li>A SocialBase utiliza proteções físicas, administrativas e técnicas comercialmente razoáveis e padrão da indústria para preservar a integridade e segurança de suas Informações Pessoais. Também utilizamos a criptografia Secure Sockets Layer (SSL) para transmitir informações confidenciais. Embora a SocialBase se esforce para proteger a segurança e integridade de Informações Pessoais delicadas fornecidas a rede, devido à natureza inerente da Internet como um veículo aberto de comunicação global, não podemos garantir que as informações, durante a transmissão através da Internet ou enquanto estiverem armazenadas em nossos sistemas ou de outra forma sob nosso cuidado, estarão seguras da intrusão de outros, como, por exemplo, hackers.</li>
    <li>Caso você entre em contato conosco por e-mail, através do “fale conosco” ou de um recurso semelhante na rede, você deve estar ciente de que sua transmissão pode não ser segura. Um terceiro não afiliado pode visualizar as informações que você envia por esses métodos em trânsito. Não teremos qualquer responsabilidade pela divulgação de suas informações devido a erros ou atos não autorizados de terceiros durante ou após a transmissão.</li>
    <li>Na hipótese improvável de acreditarmos que a segurança de suas Informações Pessoais em nossa posse ou controle pode ter sido comprometida, iremos procurar lhe notificar sobre tal fato. Nós nos esforçaremos para fazê-lo tão prontamente quanto possível nas circunstâncias e, na medida em que tivermos seu endereço de e-mail, podemos lhe notificar dessa forma. Você consente nosso uso do seu e-mail como meio para tal notificação. Caso prefira que utilizemos outro método para lhe notificar nessa situação, envie-nos um e-mail para o endereço ‘<a href="mailto:contato@SocialBase.com.br">contato@SocialBase.com.br</a>’ com as informações de contato alternativas que você deseja que sejam utilizadas.</li>
  </ul>
  <h2 id="informacoes-desta-politica">Informações gerais a respeito desta política</h2>
  <ul class="list">
    <li>Nós nos reservamos o direito de transferir qualquer informação que temos sobre você na hipótese de vendermos ou transferirmos todo ou uma fração de nosso negócio ou ativos. Caso tal venda ou transferência ocorra, envidaremos esforços razoáveis para orientar o cessionário a utilizar as informações pessoais que você forneceu através da rede de uma forma que seja consistente com esta Política de Privacidade. Caso isso ocorra, nós lhe notificaremos conforme descrito na seção “Atualizações a nossa Política de Privacidade”.</li>
    <li>Na medida em que atualizamos e expandimos nosso website e rede, esta Política de Privacidade pode ser alterada. Dessa forma, solicitamos que verifique frequentemente esta web page para obter as atualizações a nossa Política de Privacidade.</li>
    <li>Você tem o direito de se recusar a submeter Informações Pessoais através da rede, caso em que a SocialBase poderá não ser capaz de lhe prestar certos serviços. Entretanto, caso escolha fornecer Informações Pessoais para a SocialBase, nós lhe forneceremos a capacidade de acessar, corrigir, atualizar ou excluir as Informações Pessoais que você forneceu a rede e website, enviando um e-mail para ‘<a href="mailto:contato@SocialBase.com.br">contato@SocialBase.com.br</a>’. Responderemos sua solicitação no prazo de 15 dias, porém, antes de podermos lhe fornecer qualquer informação ou corrigir quaisquer inexatidões, podemos lhe solicitar que verifique sua identidade e forneça outros detalhes para nos ajudar a responder sua solicitação.</li>
    <li>Quando estiver na rede, você pode ter a oportunidade de visitar ou conectar outros websites, inclusive aqueles operados pela SocialBase ou por terceiros não afiliados. Tais websites podem coletar Informações Pessoais sobre você, e porque esta Política de Privacidade não lida com as práticas de informação desses websites, você deve analisar suas políticas de privacidade para ver como tratam suas Informações Pessoais.</li>
    <li>A rede não é dirigida a menores de dezoito anos e não coletamos intencionalmente informações pessoais de pessoas com idade inferior a essa em nossa rede. Caso tomemos conhecimento de que recebemos inadvertidamente informações pessoais de um visitante menor de dezoito anos na rede, excluiremos as informações de nossos registros.</li>
    <li>Esta Política de Privacidade pode ser atualizada periodicamente e sem lhe dar notificação prévia a fim de refletir as mudanças em nossas práticas de informação on-line. Postaremos uma notificação visível em nossa rede e website para lhe notificar sobre quaisquer mudanças significativas a nossa Política de Privacidade e indicaremos na parte superior da declaração quando foi mais recentemente atualizada.</li>
  </ul>
</article>

